library(reshape2)
library(plyr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggthemes)
library(leaflet)
library(shiny)
library(googleVis)
library(data.table)
library(scales)
library(plotly)
library(ggmap)
library(shinydashboard)

df = readRDS('./www/201605-citibike-tripdata_df.rda')
melt_df = readRDS('./www/201605-citibike-tripdata_melt.rda')
dir_df = readRDS('./www/201605-citibike-tripdata_direction.rda')